name: app
description: "혼몰 - 무료타로점집"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  flame: ^1.14.0
  http: ^1.2.0
  share_plus: ^7.2.2
  url_launcher: ^6.2.4
  kakao_flutter_sdk: ^1.8.0
  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.3.1
  webview_flutter_web: ^0.2.2+4
  change_app_package_name: ^1.1.0
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.1
  b: ^0.2.0
  loading_indicator: ^3.1.1
  flutter_animate: ^4.5.0
  flutter_picker: ^2.1.0
  flutter_spinbox: ^0.13.1
  sprintf: ^7.0.0
  mask_text_input_formatter: ^2.8.0
  numberpicker: ^2.1.2
  fluttertoast: ^8.2.4
  toast: ^0.3.0
  webview_flutter_platform_interface: ^2.10.0
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/
    - assets/spread/
    - assets/images/mars/
  
  #fonts:
  #  - family: Cute
  #    fonts:
  #      - asset: assets/fonts/CuteFont-Regular.ttf
  #  - family: Gaegu
  #    fonts:
  #      - asset: assets/fonts/Gaegu-Bold.ttf
  #  - family: ZenMaru
  #    fonts:
  #      - asset: assets/fonts/ZenMaruGothic-Bold.ttf
  